language: rust
sudo: false
rust:
  - nightly

os:
  - linux
  - osx

env:
  - FEATURES=""
  - FEATURES="--features force-inprocess"

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
  - cargo build $FEATURES
  - cargo test $FEATURES
