language: rust
sudo: false

rust:
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  include:
    - os: linux
      env: FEATURES="unstable"
    - os: linux
      env: FEATURES="unstable force-inprocess"
    - os: linux
      env: FEATURES="unstable memfd"
    - os: osx
      env: FEATURES="unstable"
    - os: osx
      env: FEATURES="unstable force-inprocess"

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
