[package]
name = "ipc-channel"
version = "0.1.0"

[lib]
name = "ipc_channel"
path = "lib.rs"

[dependencies.serde]
opt_level = 2

[dependencies]
byteorder = "*"
lazy_static = "*"
libc = "*"
rand = "*"
serde_macros = "*"

