[package]
name = "ipc-channel"
version = "0.1.0"

[lib]
name = "ipc_channel"
path = "lib.rs"

[dependencies]
libc = "*"
rand = "*"

[dependencies.serde]
path = "../serde/serde"

[dependencies.serde_macros]
path = "../serde/serde_macros"

