[package]
name = "ipc-channel"
version = "0.2.3"

[lib]
name = "ipc_channel"
path = "lib.rs"

[dependencies]
bincode = ">=0.4.1, <0.6"
lazy_static = "0.2"
libc = "0.2"
rand = "0.3"
serde = ">=0.6, <0.8"
uuid = { version = "0.2", features = ["v4"] }

[dev-dependencies]
crossbeam = "0.2"
